import { useEffect,useState } from "react";
import { api } from "../api";
import AppHeader from "../components/AppHeader";
type Props={recipeId:number;onHome:()=>void};
export default function RecipeDetailPage({recipeId,onHome}:Props){
 const [recipe,setRecipe]=useState<any>(null);const [detail,setDetail]=useState<any>(null);const [metric,setMetric]=useState(false);const [favorite,setFavorite]=useState(false);const [rating,setRating]=useState("5");const [notes,setNotes]=useState("");const [editing,setEditing]=useState(false);const [edit,setEdit]=useState<any>({});const [hideConfirm,setHideConfirm]=useState(false);const [actionError,setActionError]=useState("");const [printMode,setPrintMode]=useState(false);
 async function load(){const [display,d]=await Promise.all([api.display.recipe(recipeId,metric),api.recipes.get(recipeId)]);setRecipe(display);setDetail(d);setFavorite(d.favorite);setEdit({name:d.name,description:d.description||"",recipe_type:d.recipe_type,instructions:d.instructions||"",image_path:d.image_path||""})}
 useEffect(()=>{load()},[recipeId,metric]);if(!recipe||!detail)return <main className="page"><p>Loading recipe…</p></main>;
 async function toggleFavorite(){favorite?await api.favorites.remove(recipe.id):await api.favorites.add(recipe.id);setFavorite(!favorite)}
 async function madeThis(){await api.history.add({recipe_id:recipe.id,rating:Number(rating),notes:notes||null});setNotes("");window.alert("Added to drink history.")}
 async function saveEdit(){await api.recipes.update(recipe.id,{...edit,source_type:detail.source_type});setEditing(false);await load()}
 async function confirmHide(){setActionError("");try{await api.recipes.hide(recipe.id);onHome()}catch(err:any){setActionError(err?.message||"Could not hide this recipe.");setHideConfirm(false)}}
 function startPrint(){setPrintMode(true);setActionError("");setTimeout(()=>{try{window.print()}catch{}},150)}
 if(printMode)return <main className="page recipe-print-view"><div className="toolbar no-print"><button onClick={()=>setPrintMode(false)}>← Back to Recipe</button><button className="primary" onClick={()=>{try{window.print()}catch{}}}>Print / Save as PDF</button></div><p className="print-help no-print">If CasaOS blocks the print dialog, this page is already formatted for printing. Use your browser menu → Print, or press Ctrl+P.</p><h1 className="recipe-print-title">{recipe.name}</h1>{recipe.image_path&&<figure className="recipe-image-wrap"><img className="recipe-image" src={recipe.image_path} alt={recipe.name}/></figure>}{recipe.description&&<p className="lede">{recipe.description}</p>}<section className="detail-card"><h2>Ingredients</h2><ul>{recipe.ingredients.map((item:any)=><li key={item.ingredient_id}>{item.quantity??""} {item.unit??""} {item.name}{item.optional?" (optional)":""}</li>)}</ul></section><section className="detail-card"><h2>Instructions</h2><p>{recipe.instructions||"No instructions yet."}</p></section></main>;
 return <main className="page"><AppHeader title={recipe.name} onHome={onHome}/><h1 className="recipe-print-title print-only">{recipe.name}</h1><div className="toolbar no-print"><button className="primary" onClick={()=>setEditing(!editing)}>✎ Edit</button><button onClick={toggleFavorite}>{favorite?"★ Favorite":"☆ Add Favorite"}</button><button onClick={()=>setMetric(!metric)}>{metric?"US Units":"Metric"}</button><button onClick={startPrint}>Print Recipe</button><button className="danger-link" onClick={()=>{setHideConfirm(true);setActionError("")}}>{detail.source_type==="built_in"?"Hide Recipe":"Delete Recipe"}</button></div>
 {hideConfirm&&<section className="detail-card no-print"><h2>{detail.source_type==="built_in"?"Hide this recipe?":"Delete this recipe?"}</h2><p>{detail.source_type==="built_in"?"This built-in recipe will be hidden from your local catalog.":"This locally added recipe will be removed from your active catalog."}</p><div className="toolbar"><button className="primary" onClick={confirmHide}>{detail.source_type==="built_in"?"Yes, Hide Recipe":"Yes, Delete Recipe"}</button><button onClick={()=>setHideConfirm(false)}>Cancel</button></div></section>}
 {actionError&&<p className="error no-print">{actionError}</p>}
 {editing&&<section className="detail-card no-print"><p className="eyebrow">Local recipe edit</p>{detail.source_type==="built_in"&&<p className="lede">This changes your local copy only; the built-in identity is preserved for future updates.</p>}<label>Name<input className="wide-input" value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>Description<textarea rows={3} value={edit.description} onChange={e=>setEdit({...edit,description:e.target.value})}/></label><label>Type <select value={edit.recipe_type} onChange={e=>setEdit({...edit,recipe_type:e.target.value})}><option value="cocktail">Cocktail</option><option value="mocktail">Mocktail</option></select></label><label>Instructions<textarea rows={8} value={edit.instructions} onChange={e=>setEdit({...edit,instructions:e.target.value})}/></label><div className="toolbar"><button className="primary" onClick={saveEdit}>Save Changes</button><button onClick={()=>setEditing(false)}>Cancel</button></div></section>}
 {recipe.image_path&&<figure className="recipe-image-wrap"><img className="recipe-image" src={recipe.image_path} alt={recipe.name}/>{recipe.image_ai_generated&&<figcaption className="ai-label">AI-generated image</figcaption>}</figure>}{recipe.description&&<p className="lede">{recipe.description}</p>}<section className="detail-card"><h2>Ingredients</h2><ul>{recipe.ingredients.map((item:any)=><li key={item.ingredient_id}>{item.quantity??""} {item.unit??""} {item.name}{item.optional?" (optional)":""}</li>)}</ul></section><section className="detail-card"><h2>Instructions</h2><p>{recipe.instructions||"No instructions yet."}</p></section>
 <section className="detail-card no-print"><h2>I Made This</h2><label>Rating <select value={rating} onChange={e=>setRating(e.target.value)}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} star{n===1?"":"s"}</option>)}</select></label><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional notes" rows={4}/><button className="primary" onClick={madeThis}>Confirm Made</button></section></main>;
}
