# Virtual Bartender V8 catalog expansion.
# 25 New Era cocktails identified as missing in the 2026 IBA audit.
# Formulas normalized from current IBA references; preparation wording is original Virtual Bartender text.

UNITS_V8 = []

INGREDIENTS_V8 = [
    ("Cuban Aguardiente", "Spirits"), ("Raw Honey", "Pantry / Kitchen"), ("Water", "Mixers"),
    ("Green Chartreuse", "Liqueurs"), ("Gold Jamaican Rum", "Rum"), ("Honey Syrup", "Syrups"),
    ("Raspberry Liqueur", "Liqueurs"), ("Basil Leaves", "Fresh Ingredients"), ("Grand Marnier", "Liqueurs"),
    ("Smoky Rum", "Rum"), ("Frangelico", "Liqueurs"), ("Passion Fruit Puree", "Fresh Ingredients"),
    ("Ginger Slice", "Fresh Ingredients"), ("Mezcal", "Spirits"), ("Overproof White Rum", "Rum"),
    ("Blackstrap Rum", "Rum"), ("Peach Brandy", "Liqueurs"), ("Honey Mix", "Syrups"),
    ("Pineapple Chunks", "Fresh Ingredients"), ("Yellow Chartreuse", "Liqueurs"), ("Aperol", "Liqueurs"),
    ("Red Wine", "Wine"), ("Aged Rum", "Rum"), ("Cloves", "Pantry / Kitchen"),
    ("Vanilla Vodka", "Spirits"), ("Passion Fruit Liqueur", "Liqueurs"), ("Vanilla Sugar", "Pantry / Kitchen"),
    ("Sparkling Wine", "Sparkling Wine"), ("Amontillado Sherry", "Fortified Wine"), ("Palo Cortado Sherry", "Fortified Wine"),
    ("Orange Wheel", "Garnishes"), ("Lemon Wheel", "Garnishes"), ("Elderflower Cordial", "Mixers"),
    ("Red Chili Pepper", "Fresh Ingredients"), ("Rhum Agricole", "Rum"), ("Allspice Dram", "Liqueurs"),
    ("Irish Whiskey", "Whiskey"), ("Agave Nectar", "Syrups"), ("Orgeat Syrup", "Syrups"),
    ("White Grappa", "Brandy"), ("Chamomile Honey Mix", "Syrups"), ("Chamomile Cordial", "Mixers"),
]

RECIPES_V8 = [
    {'key':'canchanchara','name':'Canchanchara','type':'cocktail','version':'1.0','description':'Cuban aguardiente with lime, honey, and water.','instructions':'Dissolve the honey with water and lime juice in a rocks glass. Add cracked ice, pour in the aguardiente, and stir vigorously.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/canchanchara/','ingredients':[('Cuban Aguardiente',60.0,'ml',False),('Lime Juice',15.0,'ml',False),('Raw Honey',15.0,'ml',False),('Water',50.0,'ml',False)]},
    {'key':'chartreuse-swizzle','name':'Chartreuse Swizzle','type':'cocktail','version':'1.0','description':'Green Chartreuse, pineapple, lime, and falernum over pebble ice.','instructions':'Add all ingredients to a tall glass with pebble ice and swizzle vigorously. Top with more pebble ice.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/chartreuse-swizzle/','ingredients':[('Green Chartreuse',45.0,'ml',False),('Pineapple Juice',30.0,'ml',False),('Lime Juice',22.5,'ml',False),('Falernum',15.0,'ml',False)]},
    {'key':'dons-special-daiquiri','name':"Don's Special Daiquiri",'type':'cocktail','version':'1.0','description':'A tropical daiquiri with Jamaican and Cuban-style rum, passion fruit, lime, and honey.','instructions':'Blend briefly with crushed ice and pour into a footed glass. Add more crushed ice to fill.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/dons-special-daiquiri/','ingredients':[('Gold Jamaican Rum',30.0,'ml',False),('White Rum',15.0,'ml',False),('Passion Fruit Syrup',15.0,'ml',False),('Lime Juice',15.0,'ml',False),('Honey Syrup',15.0,'ml',False)]},
    {'key':'fernandito','name':'Fernandito','type':'cocktail','version':'1.0','description':'Fernet and cola over ice.','instructions':'Pour Fernet over ice in a rocks glass, fill with cola, and stir gently.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/fernandito/','ingredients':[('Fernet',50.0,'ml',False),('Cola',1.0,'top',False)]},
    {'key':'french-martini','name':'French Martini','type':'cocktail','version':'1.0','description':'Vodka, raspberry liqueur, and pineapple juice.','instructions':'Shake all ingredients with ice and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/french-martini/','ingredients':[('Vodka',45.0,'ml',False),('Raspberry Liqueur',15.0,'ml',False),('Pineapple Juice',15.0,'ml',False)]},
    {'key':'gin-basil-smash','name':'Gin Basil Smash','type':'cocktail','version':'1.0','description':'A fresh basil gin sour.','instructions':'Add all ingredients to a shaker with ice, shake vigorously, and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/gin-basil-smash/','ingredients':[('Gin',60.0,'ml',False),('Lemon Juice',22.5,'ml',False),('Simple Syrup',22.5,'ml',False),('Basil Leaves',10.0,'pc',False)]},
    {'key':'grand-margarita','name':'Grand Margarita','type':'cocktail','version':'1.0','description':'Tequila, Grand Marnier, and lime.','instructions':'Shake all ingredients hard with ice and strain into an ice-filled rocks glass, optionally with a salted rim.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/grand-margarita/','ingredients':[('Blanco Tequila',45.0,'ml',False),('Grand Marnier',30.0,'ml',False),('Lime Juice',15.0,'ml',False)]},
    {'key':'iba-tiki','name':'IBA Tiki','type':'cocktail','version':'1.0','description':'A rich tropical rum cocktail with nut liqueurs, passion fruit, pineapple, lime, and ginger.','instructions':'Muddle the ginger in a shaker, add the remaining ingredients and ice, shake vigorously, then strain over pebble ice in a tiki glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/iba-tiki/','ingredients':[('Dark Rum',30.0,'ml',False),('Smoky Rum',30.0,'ml',False),('Amaretto',15.0,'ml',False),('Frangelico',5.0,'ml',False),('Maraschino Liqueur',5.0,'drop',False),('Passion Fruit Puree',30.0,'ml',False),('Pineapple Juice',90.0,'ml',False),('Lime Juice',30.0,'ml',False),('Ginger Slice',1.0,'pc',False)]},
    {'key':'illegal','name':'Illegal','type':'cocktail','version':'1.0','description':'A mezcal sour with overproof rum, falernum, maraschino, and lime.','instructions':'Shake all ingredients vigorously with ice and strain into a chilled cocktail glass or serve over fresh ice.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/illegal/','ingredients':[('Mezcal',30.0,'ml',False),('Overproof White Rum',15.0,'ml',False),('Falernum',15.0,'ml',False),('Maraschino Liqueur',1.0,'barspoon',False),('Lime Juice',22.5,'ml',False),('Simple Syrup',15.0,'ml',False),('Egg White',3.0,'drop',True)]},
    {'key':'jungle-bird','name':'Jungle Bird','type':'cocktail','version':'1.0','description':'Blackstrap rum, Campari, pineapple, lime, and demerara syrup.','instructions':'Shake all ingredients with ice and strain into a rocks glass filled with fresh ice.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/jungle-bird/','ingredients':[('Blackstrap Rum',45.0,'ml',False),('Campari',22.5,'ml',False),('Pineapple Juice',45.0,'ml',False),('Lime Juice',15.0,'ml',False),('Demerara Syrup',15.0,'ml',False)]},
    {'key':'missionarys-downfall','name':"Missionary's Downfall",'type':'cocktail','version':'1.0','description':'A blended rum drink with peach, lime, honey, mint, and pineapple.','instructions':'Blend all ingredients with crushed ice until smooth and pour into a large chilled glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/missionarys-downfall/','ingredients':[('White Rum',30.0,'ml',False),('Peach Brandy',15.0,'ml',False),('Lime Juice',15.0,'ml',False),('Honey Mix',30.0,'ml',False),('Mint Leaves',10.0,'pc',False),('Pineapple Chunks',4.0,'pc',False)]},
    {'key':'naked-and-famous','name':'Naked and Famous','type':'cocktail','version':'1.0','description':'Equal parts mezcal, yellow Chartreuse, Aperol, and lime.','instructions':'Shake all ingredients with ice and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/naked-and-famous/','ingredients':[('Mezcal',22.5,'ml',False),('Yellow Chartreuse',22.5,'ml',False),('Aperol',22.5,'ml',False),('Lime Juice',22.5,'ml',False)]},
    {'key':'new-york-sour','name':'New York Sour','type':'cocktail','version':'1.0','description':'A rye whiskey sour finished with a red wine float.','instructions':'Shake the whiskey, syrup, lemon, and optional egg white with ice. Strain over fresh ice and float the red wine on top.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/new-york-sour/','ingredients':[('Rye Whiskey',60.0,'ml',False),('Simple Syrup',22.5,'ml',False),('Lemon Juice',30.0,'ml',False),('Egg White',3.0,'drop',True),('Red Wine',15.0,'ml',False)]},
    {'key':'old-cuban','name':'Old Cuban','type':'cocktail','version':'1.0','description':'A minty aged-rum sour topped with sparkling wine.','instructions':'Shake everything except the sparkling wine with ice and strain into a chilled cocktail glass. Top with sparkling wine.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/old-cuban/','ingredients':[('Mint Leaves',7.0,'pc',False),('Aged Rum',45.0,'ml',False),('Lime Juice',22.5,'ml',False),('Simple Syrup',30.0,'ml',False),('Angostura Bitters',2.0,'dash',False),('Prosecco',60.0,'ml',False)]},
    {'key':'pisco-punch','name':'Pisco Punch','type':'cocktail','version':'1.0','description':'Pisco with pineapple, lemon, syrup, white wine, and clove.','instructions':'Gently mash the cloves with syrup, add pisco, pineapple, and lemon, then shake with ice. Double strain, add the white wine, and stir gently.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/pisco-punch/','ingredients':[('Pisco',60.0,'ml',False),('Pineapple Juice',22.5,'ml',False),('Simple Syrup',15.0,'ml',False),('Lemon Juice',15.0,'ml',False),('Dry White Wine',30.0,'ml',False),('Cloves',3.0,'pc',False)]},
    {'key':'porn-star-martini','name':'Porn Star Martini','type':'cocktail','version':'1.0','description':'Vanilla vodka and passion fruit served with Champagne on the side.','instructions':'Shake the vodka, passion fruit liqueur, puree, and vanilla sugar with ice and double strain into a chilled cocktail glass. Serve the Champagne separately.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/porn-star-martini/','ingredients':[('Vanilla Vodka',50.0,'ml',False),('Passion Fruit Liqueur',20.0,'ml',False),('Passion Fruit Puree',50.0,'ml',False),('Vanilla Sugar',2.0,'barspoon',False),('Champagne',50.0,'ml',False)]},
    {'key':'russian-spring-punch','name':'Russian Spring Punch','type':'cocktail','version':'1.0','description':'Vodka, lemon, cassis, syrup, and sparkling wine.','instructions':'Shake everything except the sparkling wine with ice, strain into an ice-filled tall glass, and top with sparkling wine.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/russian-spring-punch/','ingredients':[('Vodka',25.0,'ml',False),('Lemon Juice',25.0,'ml',False),('Creme de Cassis',15.0,'ml',False),('Simple Syrup',10.0,'ml',False),('Sparkling Wine',1.0,'top',False)]},
    {'key':'sherry-cobbler','name':'Sherry Cobbler','type':'cocktail','version':'1.0','description':'Two styles of sherry with sugar and fresh citrus.','instructions':'Shake the sherries, sugar, and citrus wheels briskly with ice. Strain into a cup filled with crushed ice.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/sherry-cobbler/','ingredients':[('Amontillado Sherry',45.0,'ml',False),('Palo Cortado Sherry',45.0,'ml',False),('Sugar',1.0,'tsp',False),('Orange Wheel',0.5,'pc',False),('Lemon Wheel',0.5,'pc',False)]},
    {'key':'spicy-fifty','name':'Spicy Fifty','type':'cocktail','version':'1.0','description':'Vanilla vodka with elderflower, lime, honey, and chili.','instructions':'Shake all ingredients with ice and double strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/spicy-fifty/','ingredients':[('Vanilla Vodka',50.0,'ml',False),('Elderflower Cordial',15.0,'ml',False),('Lime Juice',15.0,'ml',False),('Honey Syrup',10.0,'ml',False),('Red Chili Pepper',2.0,'pc',False)]},
    {'key':'suffering-bastard','name':'Suffering Bastard','type':'cocktail','version':'1.0','description':'Cognac and gin with lime, bitters, and ginger beer.','instructions':'Shake everything except the ginger beer with ice. Pour into a tall glass and top with ginger beer.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/suffering-bastard/','ingredients':[('Cognac',30.0,'ml',False),('Gin',30.0,'ml',False),('Lime Juice',15.0,'ml',False),('Angostura Bitters',2.0,'dash',False),('Ginger Beer',1.0,'top',False)]},
    {'key':'three-dots-and-a-dash','name':'Three Dots and a Dash','type':'cocktail','version':'1.0','description':'A tiki rum blend with falernum, allspice, citrus, honey, and bitters.','instructions':'Flash blend all ingredients with crushed ice, pour into a footed glass, and add more crushed ice.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/three-dots-and-a-dash/','ingredients':[('Rhum Agricole',45.0,'ml',False),('Aged Rum',15.0,'ml',False),('Falernum',7.5,'ml',False),('Allspice Dram',7.5,'ml',False),('Lime Juice',15.0,'ml',False),('Orange Juice',15.0,'ml',False),('Honey Syrup',15.0,'ml',False),('Angostura Bitters',2.0,'dash',False)]},
    {'key':'tipperary','name':'Tipperary','type':'cocktail','version':'1.0','description':'Irish whiskey with sweet vermouth, Green Chartreuse, and bitters.','instructions':'Stir all ingredients with ice until chilled and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/tipperary/','ingredients':[('Irish Whiskey',50.0,'ml',False),('Sweet Vermouth',25.0,'ml',False),('Green Chartreuse',15.0,'ml',False),('Angostura Bitters',2.0,'dash',False)]},
    {'key':'tommys-margarita','name':"Tommy's Margarita",'type':'cocktail','version':'1.0','description':'A Margarita variation using agave nectar instead of orange liqueur.','instructions':'Shake all ingredients with ice and strain into an ice-filled rocks glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/tommys-margarita/','parent':'margarita','ingredients':[('Blanco Tequila',60.0,'ml',False),('Lime Juice',30.0,'ml',False),('Agave Nectar',30.0,'ml',False)]},
    {'key':'trinidad-sour','name':'Trinidad Sour','type':'cocktail','version':'1.0','description':'A bitters-forward sour with orgeat, lemon, and rye.','instructions':'Shake all ingredients with ice and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/trinidad-sour/','ingredients':[('Angostura Bitters',45.0,'ml',False),('Orgeat Syrup',30.0,'ml',False),('Lemon Juice',22.5,'ml',False),('Rye Whiskey',15.0,'ml',False)]},
    {'key':'ve-n-to','name':'Ve.N.To','type':'cocktail','version':'1.0','description':'White grappa with lemon, chamomile-honey sweetness, and optional egg white.','instructions':'Shake all ingredients vigorously with ice and strain into a small rocks glass filled with fresh ice.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/ve-n-to/','ingredients':[('White Grappa',45.0,'ml',False),('Lemon Juice',22.5,'ml',False),('Chamomile Honey Mix',15.0,'ml',False),('Chamomile Cordial',15.0,'ml',False),('Egg White',3.0,'drop',True)]},
]
