# Virtual Bartender V6 catalog expansion.
# Formulas are normalized from the IBA official cocktail references; preparation text is original Virtual Bartender wording.

UNITS_V6 = [
    {"name": "milliliter", "abbreviation": "ml", "metric_equivalent": 1.0, "metric_unit": "ml"},
    {"name": "bar spoon", "abbreviation": "barspoon", "metric_equivalent": 5.0, "metric_unit": "ml"},
    {"name": "drop", "abbreviation": "drop", "metric_equivalent": None, "metric_unit": None},
    {"name": "splash", "abbreviation": "splash", "metric_equivalent": None, "metric_unit": None},
    {"name": "rim", "abbreviation": "rim", "metric_equivalent": None, "metric_unit": None},
    {"name": "pinch", "abbreviation": "pinch", "metric_equivalent": None, "metric_unit": None},
    {"name": "top", "abbreviation": "top", "metric_equivalent": None, "metric_unit": None},
]

INGREDIENTS_V6 = [
    ("Apricot Brandy", "Liqueurs"), ("Calvados", "Brandy"), ("Cognac", "Brandy"),
    ("Brandy", "Brandy"), ("Maraschino Liqueur", "Liqueurs"), ("Orange Liqueur", "Liqueurs"),
    ("Aromatic Bitters", "Bitters"), ("Citrus Peel", "Garnishes"), ("Old Tom Gin", "Spirits"),
    ("Orange Bitters", "Bitters"), ("Raspberry Syrup", "Syrups"), ("Soda Water", "Mixers"),
    ("London Dry Gin", "Spirits"), ("Fernet", "Liqueurs"), ("Tawny Port", "Fortified Wine"),
    ("Egg Yolk", "Fresh Ingredients"), ("Nutmeg", "Pantry / Kitchen"), ("Cream", "Dairy"),
    ("Orange Flower Water", "Mixers"), ("Vanilla Extract", "Pantry / Kitchen"),
    ("Cherry Brandy", "Liqueurs"), ("Absinthe", "Spirits"), ("White Creme de Menthe", "Liqueurs"),
    ("Benedictine", "Liqueurs"), ("Peychaud's Bitters", "Bitters"),
]

RECIPES_V6 = [
    {'key':'angel-face','name':'Angel Face','type':'cocktail','version':'1.0','description':'A spirit-forward gin, apricot brandy, and Calvados classic.','instructions':'Shake all ingredients with ice and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/angel-face/','ingredients':[('Gin',30.0,'ml',False),('Apricot Brandy',30.0,'ml',False),('Calvados',30.0,'ml',False)]},
    {'key':'between-the-sheets','name':'Between the Sheets','type':'cocktail','version':'1.0','description':'Rum and Cognac brightened with orange liqueur and lemon.','instructions':'Shake all ingredients with ice and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/between-the-sheets/','ingredients':[('White Rum',30.0,'ml',False),('Cognac',30.0,'ml',False),('Triple Sec',30.0,'ml',False),('Lemon Juice',20.0,'ml',False)]},
    {'key':'brandy-crusta','name':'Brandy Crusta','type':'cocktail','version':'1.0','description':'Brandy with maraschino, citrus, syrup, and aromatic bitters.','instructions':'Stir the liquid ingredients with ice and strain into a sugar-rimmed cocktail glass. Add a broad citrus peel inside the glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/brandy-crusta/','ingredients':[('Brandy',52.5,'ml',False),('Maraschino Liqueur',7.5,'ml',False),('Orange Liqueur',1.0,'barspoon',False),('Lemon Juice',15.0,'ml',False),('Simple Syrup',1.0,'barspoon',False),('Aromatic Bitters',2.0,'dash',False),('Sugar',1.0,'rim',True),('Citrus Peel',1.0,'pc',True)]},
    {'key':'casino','name':'Casino','type':'cocktail','version':'1.0','description':'Old Tom gin with maraschino, lemon, and orange bitters.','instructions':'Shake all ingredients with ice and strain into a chilled rocks glass over fresh ice.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/casino/','ingredients':[('Old Tom Gin',40.0,'ml',False),('Maraschino Liqueur',10.0,'ml',False),('Lemon Juice',10.0,'ml',False),('Orange Bitters',2.0,'dash',False)]},
    {'key':'clover-club','name':'Clover Club','type':'cocktail','version':'1.0','description':'A tart raspberry gin sour with egg white.','instructions':'Shake all ingredients thoroughly with ice and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/clover-club/','ingredients':[('Gin',45.0,'ml',False),('Raspberry Syrup',15.0,'ml',False),('Lemon Juice',15.0,'ml',False),('Egg White',3.0,'drop',False)]},
    {'key':'gin-fizz','name':'Gin Fizz','type':'cocktail','version':'1.0','description':'A refreshing gin sour lengthened with soda.','instructions':'Shake gin, lemon juice, and syrup with ice. Strain into a tall glass without ice and finish with a splash of soda water.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/gin-fizz/','ingredients':[('Gin',45.0,'ml',False),('Lemon Juice',30.0,'ml',False),('Simple Syrup',10.0,'ml',False),('Soda Water',1.0,'splash',False)]},
    {'key':'hanky-panky','name':'Hanky Panky','type':'cocktail','version':'1.0','description':'Gin and sweet vermouth sharpened with Fernet.','instructions':'Stir all ingredients with ice and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/hanky-panky/','ingredients':[('London Dry Gin',45.0,'ml',False),('Sweet Vermouth',45.0,'ml',False),('Fernet',7.5,'ml',False)]},
    {'key':'martinez','name':'Martinez','type':'cocktail','version':'1.0','description':'Gin and sweet vermouth with maraschino and orange bitters.','instructions':'Stir all ingredients with ice and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/martinez/','ingredients':[('London Dry Gin',45.0,'ml',False),('Sweet Vermouth',45.0,'ml',False),('Maraschino Liqueur',1.0,'barspoon',False),('Orange Bitters',2.0,'dash',False)]},
    {'key':'mary-pickford','name':'Mary Pickford','type':'cocktail','version':'1.0','description':'White rum with pineapple, maraschino, and grenadine.','instructions':'Shake all ingredients with ice and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/mary-pickford/','ingredients':[('White Rum',45.0,'ml',False),('Pineapple Juice',45.0,'ml',False),('Maraschino Liqueur',7.5,'ml',False),('Grenadine',5.0,'ml',False)]},
    {'key':'monkey-gland','name':'Monkey Gland','type':'cocktail','version':'1.0','description':'Gin and orange juice accented by absinthe and grenadine.','instructions':'Shake all ingredients with ice and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/monkey-gland/','ingredients':[('Gin',45.0,'ml',False),('Orange Juice',45.0,'ml',False),('Absinthe',1.0,'tbsp',False),('Grenadine',1.0,'tbsp',False)]},
    {'key':'paradise','name':'Paradise','type':'cocktail','version':'1.0','description':'Gin, apricot brandy, and orange juice.','instructions':'Shake all ingredients with ice and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/paradise/','ingredients':[('Gin',30.0,'ml',False),('Apricot Brandy',20.0,'ml',False),('Orange Juice',15.0,'ml',False)]},
    {'key':'porto-flip','name':'Porto Flip','type':'cocktail','version':'1.0','description':'A rich brandy and tawny port flip.','instructions':'Shake all ingredients with ice and strain into a chilled cocktail glass. Finish with freshly grated nutmeg if desired.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/porto-flip/','ingredients':[('Brandy',15.0,'ml',False),('Tawny Port',45.0,'ml',False),('Egg Yolk',10.0,'ml',False),('Nutmeg',1.0,'pinch',True)]},
    {'key':'ramos-fizz','name':'Ramos Fizz','type':'cocktail','version':'1.0','description':'A creamy citrus gin fizz with egg white and orange flower water.','instructions':'Shake everything except soda water very thoroughly with ice. Strain, shake again without ice for a dense foam, pour into a highball glass, and top with soda water.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/ramos-fizz/','ingredients':[('Gin',45.0,'ml',False),('Lime Juice',15.0,'ml',False),('Lemon Juice',15.0,'ml',False),('Simple Syrup',30.0,'ml',False),('Cream',60.0,'ml',False),('Egg White',30.0,'ml',False),('Orange Flower Water',3.0,'dash',False),('Vanilla Extract',2.0,'drop',False),('Soda Water',1.0,'top',False)]},
    {'key':'remember-the-maine','name':'Remember the Maine','type':'cocktail','version':'1.0','description':'Rye, sweet vermouth, cherry brandy, and an absinthe rinse.','instructions':'Rinse a chilled coupe with absinthe and discard the excess. Stir the remaining ingredients with ice and strain into the prepared glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/remember-the-maine/','ingredients':[('Rye Whiskey',60.0,'ml',False),('Sweet Vermouth',22.5,'ml',False),('Cherry Brandy',15.0,'ml',False),('Absinthe',7.5,'ml',False)]},
    {'key':'stinger','name':'Stinger','type':'cocktail','version':'1.0','description':'Cognac and white crème de menthe.','instructions':'Stir both ingredients with ice and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/stinger/','ingredients':[('Cognac',50.0,'ml',False),('White Creme de Menthe',20.0,'ml',False)]},
    {'key':'tuxedo','name':'Tuxedo','type':'cocktail','version':'1.0','description':'Old Tom gin and dry vermouth accented with maraschino, absinthe, and orange bitters.','instructions':'Stir all ingredients with ice and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/tuxedo/','ingredients':[('Old Tom Gin',30.0,'ml',False),('Dry Vermouth',30.0,'ml',False),('Maraschino Liqueur',0.5,'barspoon',False),('Absinthe',0.25,'barspoon',False),('Orange Bitters',3.0,'dash',False)]},
    {'key':'vieux-carre','name':'Vieux Carré','type':'cocktail','version':'1.0','description':'Rye and Cognac with sweet vermouth, Bénédictine, and Peychaud’s bitters.','instructions':'Stir all ingredients with ice and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/vieux-carre/','ingredients':[('Rye Whiskey',30.0,'ml',False),('Cognac',30.0,'ml',False),('Sweet Vermouth',30.0,'ml',False),('Benedictine',1.0,'barspoon',False),("Peychaud's Bitters",2.0,'dash',False)]},
    {'key':'white-lady','name':'White Lady','type':'cocktail','version':'1.0','description':'A crisp gin, orange liqueur, and lemon sour.','instructions':'Shake all ingredients with ice and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/white-lady/','ingredients':[('Gin',40.0,'ml',False),('Triple Sec',30.0,'ml',False),('Lemon Juice',20.0,'ml',False)]},
]
