# Virtual Bartender V7 catalog expansion.
# Contemporary Classics identified as missing in the 2026 IBA audit.
# Preparation wording is original Virtual Bartender text.

UNITS_V7 = []

INGREDIENTS_V7 = [
    ("Cachaca", "Spirits"), ("Lime", "Fresh Ingredients"), ("Pisco", "Brandy"),
    ("Green Creme de Menthe", "Liqueurs"), ("White Creme de Cacao", "Liqueurs"),
    ("Prosecco", "Sparkling Wine"), ("Dry White Wine", "Wine"), ("Creme de Cassis", "Liqueurs"),
    ("Lillet Blanc", "Fortified Wine"), ("Cherry Liqueur", "Liqueurs"), ("Falernum", "Liqueurs"),
    ("Demerara Syrup", "Syrups"), ("Cinnamon Syrup", "Syrups"),
    ("Amaretto", "Liqueurs"), ("Cynar", "Liqueurs"),
]

RECIPES_V7 = [
    {'key':'caipirinha','name':'Caipirinha','type':'cocktail','version':'1.0','description':'Brazilian cachaça with fresh lime and sugar.','instructions':'Place the lime and sugar in a rocks glass and gently muddle to release the juice and oils. Fill with ice, add cachaça, and stir well.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/caipirinha/','ingredients':[('Cachaca',60.0,'ml',False),('Lime',1.0,'pc',False),('Sugar',4.0,'tsp',False)]},
    {'key':'cardinale','name':'Cardinale','type':'cocktail','version':'1.0','description':'A dry gin, vermouth, and Campari aperitif.','instructions':'Stir all ingredients with ice until chilled, then strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/cardinale/','ingredients':[('Gin',40.0,'ml',False),('Dry Vermouth',20.0,'ml',False),('Campari',10.0,'ml',False)]},
    {'key':'corpse-reviver-2','name':'Corpse Reviver #2','type':'cocktail','version':'1.0','description':'Gin, orange liqueur, aromatized wine, lemon, and absinthe.','instructions':'Shake the liquid ingredients with ice and strain into a chilled cocktail glass lightly rinsed with absinthe.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/corpse-reviver-2/','ingredients':[('Gin',30.0,'ml',False),('Cointreau',30.0,'ml',False),('Lillet Blanc',30.0,'ml',False),('Lemon Juice',30.0,'ml',False),('Absinthe',1.0,'dash',False)]},
    {'key':'french-connection','name':'French Connection','type':'cocktail','version':'1.0','description':'Cognac softened with amaretto.','instructions':'Build the ingredients over ice in a rocks glass and stir gently until chilled.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/french-connection/','ingredients':[('Cognac',35.0,'ml',False),('Amaretto',35.0,'ml',False)]},
    {'key':'garibaldi','name':'Garibaldi','type':'cocktail','version':'1.0','description':'Campari lengthened with fresh orange juice.','instructions':'Build Campari and orange juice over ice in a highball glass and stir gently.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/garibaldi/','ingredients':[('Campari',45.0,'ml',False),('Orange Juice',120.0,'ml',False)]},
    {'key':'grasshopper','name':'Grasshopper','type':'cocktail','version':'1.0','description':'A creamy mint and cacao after-dinner cocktail.','instructions':'Shake all ingredients with ice until well chilled and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/grasshopper/','ingredients':[('Green Creme de Menthe',20.0,'ml',False),('White Creme de Cacao',20.0,'ml',False),('Cream',20.0,'ml',False)]},
    {'key':'hemingway-special','name':'Hemingway Special','type':'cocktail','version':'1.0','description':'A dry rum sour with grapefruit and maraschino.','instructions':'Shake all ingredients with ice and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/hemingway-special/','ingredients':[('White Rum',60.0,'ml',False),('Grapefruit Juice',40.0,'ml',False),('Maraschino Liqueur',15.0,'ml',False),('Lime Juice',15.0,'ml',False)]},
    {'key':'horses-neck','name':'Horse’s Neck','type':'cocktail','version':'1.0','description':'Brandy and ginger ale with aromatic bitters.','instructions':'Build the brandy and ginger ale over ice in a highball glass. Add bitters and stir gently.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/horses-neck/','ingredients':[('Brandy',40.0,'ml',False),('Ginger Ale',120.0,'ml',False),('Angostura Bitters',1.0,'dash',False)]},
    {'key':'kir','name':'Kir','type':'cocktail','version':'1.0','description':'Dry white wine flavored with crème de cassis.','instructions':'Pour crème de cassis into a wine glass, add well-chilled dry white wine, and stir gently.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/kir/','ingredients':[('Creme de Cassis',10.0,'ml',False),('Dry White Wine',90.0,'ml',False)]},
    {'key':'lemon-drop-martini','name':'Lemon Drop Martini','type':'cocktail','version':'1.0','description':'A bright vodka cocktail with citrus and orange liqueur.','instructions':'Shake all ingredients with ice and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/lemon-drop-martini/','ingredients':[('Vodka',30.0,'ml',False),('Triple Sec',20.0,'ml',False),('Lemon Juice',15.0,'ml',False)]},
    {'key':'long-island-iced-tea','name':'Long Island Iced Tea','type':'cocktail','version':'1.0','description':'A multi-spirit highball balanced with citrus, syrup, and cola.','instructions':'Add the spirits, lemon juice, and syrup to an ice-filled highball glass. Stir, top with cola, and stir gently once more.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/long-island-iced-tea/','ingredients':[('Vodka',15.0,'ml',False),('Blanco Tequila',15.0,'ml',False),('White Rum',15.0,'ml',False),('Gin',15.0,'ml',False),('Triple Sec',15.0,'ml',False),('Lemon Juice',25.0,'ml',False),('Simple Syrup',30.0,'ml',False),('Cola',1.0,'top',False)]},
    {'key':'mimosa','name':'Mimosa','type':'cocktail','version':'1.0','description':'Sparkling wine and orange juice.','instructions':'Pour the chilled orange juice into a flute and gently add the sparkling wine.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/mimosa/','ingredients':[('Prosecco',75.0,'ml',False),('Orange Juice',75.0,'ml',False)]},
    {'key':'pisco-sour','name':'Pisco Sour','type':'cocktail','version':'1.0','description':'Pisco with lemon, syrup, egg white, and aromatic bitters.','instructions':'Shake pisco, lemon juice, syrup, and egg white vigorously, then shake again with ice. Strain into a chilled glass and finish with bitters on the foam.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/pisco-sour/','ingredients':[('Pisco',60.0,'ml',False),('Lemon Juice',30.0,'ml',False),('Simple Syrup',20.0,'ml',False),('Egg White',1.0,'pc',False),('Angostura Bitters',3.0,'dash',True)]},
    {'key':'rabo-de-galo','name':'Rabo de Galo','type':'cocktail','version':'1.0','description':'A Brazilian cachaça aperitif with sweet vermouth and Cynar-style bitterness.','instructions':'Stir the ingredients with ice until chilled and strain into a small chilled glass or serve over fresh ice.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/rabo-de-galo/','ingredients':[('Cachaca',60.0,'ml',False),('Sweet Vermouth',20.0,'ml',False),('Cynar',15.0,'ml',False)]},
    {'key':'singapore-sling','name':'Singapore Sling','type':'cocktail','version':'1.0','description':'A complex gin sling with cherry, citrus, pineapple, herbal liqueur, and bitters.','instructions':'Shake all ingredients with ice and strain into an ice-filled highball glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/singapore-sling/','ingredients':[('Gin',30.0,'ml',False),('Cherry Liqueur',15.0,'ml',False),('Cointreau',7.5,'ml',False),('Benedictine',7.5,'ml',False),('Pineapple Juice',120.0,'ml',False),('Lime Juice',15.0,'ml',False),('Grenadine',10.0,'ml',False),('Angostura Bitters',1.0,'dash',False)]},
    {'key':'vesper','name':'Vesper','type':'cocktail','version':'1.0','description':'A strong gin and vodka cocktail with Lillet Blanc.','instructions':'Shake all ingredients with ice until very cold and strain into a chilled cocktail glass.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/vesper/','ingredients':[('Gin',45.0,'ml',False),('Vodka',15.0,'ml',False),('Lillet Blanc',7.5,'ml',False)]},
    {'key':'zombie','name':'Zombie','type':'cocktail','version':'1.0','description':'A powerful tropical rum cocktail with citrus, syrups, liqueur, and bitters.','instructions':'Shake the ingredients with ice and strain into a tall glass filled with crushed or fresh ice.','source':'IBA reference; Virtual Bartender normalized recipe','url':'https://iba-world.com/iba-cocktail/zombie/','ingredients':[('White Rum',45.0,'ml',False),('Dark Rum',45.0,'ml',False),('Falernum',15.0,'ml',False),('Lime Juice',20.0,'ml',False),('Grapefruit Juice',15.0,'ml',False),('Demerara Syrup',10.0,'ml',False),('Cinnamon Syrup',5.0,'ml',False),('Grenadine',5.0,'ml',False),('Angostura Bitters',1.0,'dash',False)]},
]
