RECIPES_V3 = [
    {"key":"vodka-tonic","name":"Vodka Tonic","type":"cocktail","version":"1.0",
     "description":"A simple vodka highball with tonic.",
     "instructions":"Build vodka and tonic water over ice and stir gently.",
     "source":"Virtual Bartender curated highball","url":"local://virtual-bartender/curated",
     "ingredients":[("Vodka",2.0,"oz",False),("Tonic Water",4.0,"oz",False),("Lime Wedge",1.0,"pc",True)]},
    {"key":"rum-cola","name":"Rum and Cola","type":"cocktail","version":"1.0",
     "description":"A straightforward rum and cola highball.",
     "instructions":"Build rum and cola over ice and stir gently.",
     "source":"Virtual Bartender curated highball","url":"local://virtual-bartender/curated",
     "ingredients":[("White Rum",2.0,"oz",False),("Cola",4.0,"oz",False)]},
    {"key":"bourbon-cola","name":"Bourbon and Cola","type":"cocktail","version":"1.0",
     "description":"Bourbon topped with cola.",
     "instructions":"Build bourbon and cola over ice and stir gently.",
     "source":"Virtual Bartender curated highball","url":"local://virtual-bartender/curated",
     "ingredients":[("Bourbon",2.0,"oz",False),("Cola",4.0,"oz",False)]},
    {"key":"scotch-soda","name":"Scotch and Soda","type":"cocktail","version":"1.0",
     "description":"Scotch lengthened with soda water.",
     "instructions":"Build Scotch over ice, top with club soda, and stir gently.",
     "source":"Virtual Bartender curated highball","url":"local://virtual-bartender/curated",
     "ingredients":[("Scotch Whisky",2.0,"oz",False),("Club Soda",4.0,"oz",False)]},
    {"key":"gin-rickey","name":"Gin Rickey","type":"cocktail","version":"1.0",
     "description":"A dry gin highball with lime and soda.",
     "instructions":"Build gin and lime over ice, top with club soda, and stir.",
     "source":"Classic reference","url":"https://en.wikibooks.org/wiki/Bartending/Cocktails",
     "ingredients":[("Gin",2.0,"oz",False),("Lime Juice",0.75,"oz",False),("Club Soda",4.0,"oz",False)]},
    {"key":"greyhound","name":"Greyhound","type":"cocktail","version":"1.0",
     "description":"Vodka and grapefruit juice over ice.",
     "instructions":"Build vodka and grapefruit juice over ice and stir.",
     "source":"Classic reference","url":"https://en.wikibooks.org/wiki/Bartending/Cocktails",
     "ingredients":[("Vodka",2.0,"oz",False),("Grapefruit Juice",4.0,"oz",False)]},
    {"key":"cape-codder","name":"Cape Codder","type":"cocktail","version":"1.0",
     "description":"Vodka and cranberry juice with an optional lime garnish.",
     "instructions":"Build vodka and cranberry juice over ice and stir gently.",
     "source":"Classic reference","url":"https://en.wikibooks.org/wiki/Bartending/Cocktails",
     "ingredients":[("Vodka",2.0,"oz",False),("Cranberry Juice",4.0,"oz",False),("Lime Wedge",1.0,"pc",True)]},
    {"key":"screwdriver","name":"Screwdriver","type":"cocktail","version":"1.0",
     "description":"Vodka and orange juice.",
     "instructions":"Build vodka and orange juice over ice and stir.",
     "source":"Classic reference","url":"https://en.wikibooks.org/wiki/Bartending/Cocktails",
     "ingredients":[("Vodka",2.0,"oz",False),("Orange Juice",4.0,"oz",False)]},
    {"key":"salty-dog","name":"Salty Dog","type":"cocktail","version":"1.0",
     "description":"A salted-rim grapefruit and vodka highball.",
     "instructions":"Salt the rim if desired, then build vodka and grapefruit juice over ice.",
     "source":"Classic reference","url":"https://en.wikibooks.org/wiki/Bartending/Cocktails",
     "ingredients":[("Vodka",2.0,"oz",False),("Grapefruit Juice",4.0,"oz",False),("Salt",1.0,"tsp",True)]},
    {"key":"rum-punch","name":"Rum Punch","type":"cocktail","version":"1.0",
     "description":"A fruity rum punch with citrus and pineapple.",
     "instructions":"Shake rum and juices with ice, strain over fresh ice, and add grenadine.",
     "source":"Virtual Bartender curated punch","url":"local://virtual-bartender/curated",
     "ingredients":[("Dark Rum",1.5,"oz",False),("White Rum",1.0,"oz",False),("Orange Juice",1.5,"oz",False),("Pineapple Juice",1.5,"oz",False),("Lime Juice",0.5,"oz",False),("Grenadine",0.25,"oz",False)]},
    {"key":"planters-punch","name":"Planter's Punch","type":"cocktail","version":"1.0",
     "description":"A rum punch with citrus, sugar, and bitters.",
     "instructions":"Shake rum, lime, syrup, and bitters with ice and strain over fresh ice.",
     "source":"IBA reference","url":"https://iba-world.com/cocktails/",
     "ingredients":[("Dark Rum",2.0,"oz",False),("Lime Juice",1.0,"oz",False),("Simple Syrup",0.75,"oz",False),("Angostura Bitters",3.0,"dash",False)]},
    {"key":"amaretto-sour","name":"Amaretto Sour","type":"cocktail","version":"1.0",
     "description":"A sweet-tart amaretto sour.",
     "instructions":"Shake amaretto, lemon, and syrup with ice and strain over fresh ice.",
     "source":"Virtual Bartender curated classic","url":"local://virtual-bartender/curated",
     "ingredients":[("Amaretto",2.0,"oz",False),("Lemon Juice",1.0,"oz",False),("Simple Syrup",0.5,"oz",False)]},
    {"key":"bramble","name":"Bramble","type":"cocktail","version":"1.0",
     "description":"A gin sour with berry sweetness.",
     "instructions":"Shake gin, lemon, and syrup with ice, strain over crushed ice, and finish with raspberry syrup.",
     "source":"IBA reference","url":"https://iba-world.com/cocktails/",
     "ingredients":[("Gin",2.0,"oz",False),("Lemon Juice",1.0,"oz",False),("Simple Syrup",0.5,"oz",False),("Raspberry Syrup",0.5,"oz",False)]},
    {"key":"southside","name":"Southside","type":"cocktail","version":"1.0",
     "description":"A minty gin sour.",
     "instructions":"Shake gin, lime, syrup, and mint with ice, then strain into a chilled glass.",
     "source":"Classic reference","url":"https://en.wikibooks.org/wiki/Bartending/Cocktails",
     "ingredients":[("Gin",2.0,"oz",False),("Lime Juice",0.75,"oz",False),("Simple Syrup",0.75,"oz",False),("Mint Leaves",6.0,"pc",False)]},
    {"key":"gold-rush","name":"Gold Rush","type":"cocktail","version":"1.0",
     "description":"A bourbon sour sweetened with honey.",
     "instructions":"Shake bourbon, lemon, and honey syrup with ice and strain over fresh ice.",
     "source":"Virtual Bartender curated modern classic","url":"local://virtual-bartender/curated",
     "ingredients":[("Bourbon",2.0,"oz",False),("Lemon Juice",0.75,"oz",False),("Honey Syrup",0.75,"oz",False)]},
    {"key":"penicillin","name":"Penicillin","type":"cocktail","version":"1.0",
     "description":"A smoky Scotch sour with honey and ginger character.",
     "instructions":"Shake Scotch, lemon, and honey syrup with ice and strain over fresh ice.",
     "source":"Virtual Bartender curated modern classic","url":"local://virtual-bartender/curated",
     "ingredients":[("Scotch Whisky",2.0,"oz",False),("Lemon Juice",0.75,"oz",False),("Honey Syrup",0.75,"oz",False),("Ginger Beer",0.5,"oz",True)]},
    {"key":"paper-plane","name":"Paper Plane","type":"cocktail","version":"1.0",
     "description":"A bittersweet bourbon sour built in equal parts.",
     "instructions":"Shake bourbon, Aperol, amaretto, and lemon juice with ice and strain into a chilled glass.",
     "source":"Virtual Bartender curated modern classic","url":"local://virtual-bartender/curated",
     "ingredients":[("Bourbon",0.75,"oz",False),("Aperol",0.75,"oz",False),("Amaretto",0.75,"oz",False),("Lemon Juice",0.75,"oz",False)]},
    {"key":"mocktail-sunrise","name":"Sunrise Mocktail","type":"mocktail","version":"1.0",
     "description":"Orange juice and grenadine with a soda finish.",
     "instructions":"Build orange juice over ice, add grenadine slowly, and top with club soda.",
     "source":"Virtual Bartender curated mocktail","url":"local://virtual-bartender/curated",
     "ingredients":[("Orange Juice",4.0,"oz",False),("Grenadine",0.5,"oz",False),("Club Soda",2.0,"oz",False)]},
    {"key":"pineapple-fizz","name":"Pineapple Fizz","type":"mocktail","version":"1.0",
     "description":"A pineapple and lime sparkling mocktail.",
     "instructions":"Shake pineapple and lime with ice, strain over fresh ice, and top with club soda.",
     "source":"Virtual Bartender curated mocktail","url":"local://virtual-bartender/curated",
     "ingredients":[("Pineapple Juice",3.0,"oz",False),("Lime Juice",0.75,"oz",False),("Simple Syrup",0.5,"oz",False),("Club Soda",2.0,"oz",False)]},
    {"key":"cranberry-lime-spritz","name":"Cranberry Lime Spritz","type":"mocktail","version":"1.0",
     "description":"A tart cranberry and lime spritz.",
     "instructions":"Build cranberry and lime over ice, top with club soda, and stir.",
     "source":"Virtual Bartender curated mocktail","url":"local://virtual-bartender/curated",
     "ingredients":[("Cranberry Juice",3.0,"oz",False),("Lime Juice",0.75,"oz",False),("Club Soda",3.0,"oz",False)]},
]
