name: virtual-bartender

services:
  backend:
    build:
      context: https://github.com/rpiammocan/virtual-bartender.git#main
      dockerfile: backend/Dockerfile.ghcr
    container_name: virtual-bartender-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: sqlite:////data/bartender.db
      BACKUPS_PATH: /backups
      MEDIA_PATH: /app/images
    volumes:
      - /DATA/AppData/virtual-bart